services:
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: home_solutions
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=home_solutions
    volumes:
      - ./backend:/app
      - /app/go/pkg
    depends_on:
      mysql:
        condition: service_healthy
    command: air # Assuming you use the air tool for live reload

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: npm start # Development server

volumes:
  db_data:
